Backend/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.login_user_view, name='login'),
    path('signup/', views.create_user_view, name='signup'),
    path('logout/', views.logout_user_view, name='logout'),
]

Backend/checkbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls')),
    path('', include('accounts.urls')),
]

Backend/register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.TransactionListView.as_view(), name='trans_list'),
    path('<int:id>/transaction/', views.TransactionDeleteView.as_view(), name='tran_del'),
    path('legend/', views.LegendCodeListView.as_view(), name='legend_code_list'),
    path('<int:id>/legend/', views.LegendCodeDeleteView.as_view(), name='code_del'),
]

Backend/register/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from .signals import calculate_current_balance_signal

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=000.00)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Transactions(models.Model):
    code = models.CharField(max_length=3)
    date =  models.DateField(auto_now=False, auto_now_add=False)
    transactions_description = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=000.00)
    transactions_type = models.TextField(max_length=6, default=None)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
    )


    def __str__(self):
        return self.code


class Legend(models.Model):
    code = models.CharField(max_length=3)
    transactions_category = models.CharField(max_length=50)
    transactions_type = models.TextField(max_length=6)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.code

Backend/register/forms.py
from django.forms import ModelForm, DateInput, Select, ModelChoiceField
from .models import Transactions, Legend

class Trans_form(ModelForm):

    class Meta:
        model = Transactions
        fields = [
            'code',
            'date',
            'transactions_description',
            'amount',
            
        ]

        widgets = {
            'date': DateInput(attrs={'class':"datepicker"}),
        }


class Legend_Form(ModelForm):
    class Meta:
        model = Legend
        fields = [
            'code',
            'transactions_category',
            'transactions_type',
        ]

Backend/register/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelChoiceField
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponse
from .models import Transactions, Legend, Profile
from django.views import View
from django.db.models import Q
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from register.mixins import CalculateCurrentBalanceMixins
from . import forms

import sys

# Create your views here.

'''
This Register View class allow a user to input and view all transactions of that user
'''
class TransactionListView(CalculateCurrentBalanceMixins, View):

    def get(self, request):
        #gets the User's ID from the request object
        user_id = request.user.id
        #query for all transactons make by the user
        transactions = Transactions.objects.filter(author=user_id)
        legend = Legend.objects.filter(author=user_id)
        #gets the profile of the user
        profile = Profile.objects.get(user=user_id)
        #the user balance that is in the profile
        bal = profile.balance

        form = forms.Trans_form()
        queryset=Legend.objects.filter(author=user_id)
        form.fields['code'] = ModelChoiceField(queryset,to_field_name="code")
        context = {
            'transactions' : transactions,
            'legend': legend,
            'form': form,
            'profile': profile,
            'bal': bal
        }
        return render(request, 'register/index.html', context)

    def post(self, request):
        # Instance of Transaction Form
        form = forms.Trans_form(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            trans_code_form_input = instance.code
            user_id = request.user.id

            code_query = Legend.objects.get(Q(code='abc') & Q(author=1)).transactions_type
            instance.author = request.user
            instance.transactions_type = str(code_query)
            instance.save()
            return redirect('register:trans_list')
        else:
            return redirect('register:trans_list')

class TransactionDeleteView(View):
    def get(self, request, id=None):
        trans_object = get_object_or_404(Transactions, id=id)
        trans_object.delete()
        #message.sucess(request, "Sucessfully deleted")
        return redirect('register:trans_list')

class LegendCodeListView(View):
    def get(self, request):
        form = forms.Legend_Form()
        user_id = request.user.id
        legend = Legend.objects.filter(author=user_id)
        context = {
            'legend': legend,
            'form': form,
        }
        print(request)
        return render(request, 'register/legend.html', context)

    def post(self, request):
        print(request.body)
        form = forms.Legend_Form(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('register:legend_code_list')

class LegendCodeDeleteView(View):
    def get(self, request, id=None):
        legend_object = get_object_or_404(Legend, id=id)
        legend_object.delete()
        return redirect('register:legend_code_list')

@receiver(pre_delete, sender=Transactions)
def update_balance_delete(sender, instance, **kwards):
    trans = Transactions.objects.get(id=instance.id)
    trans_type = trans.transactions_type

    user = instance.author
    profile_bal = Profile.objects.get(user=user).balance
    trans_amount = trans.amount

    if trans_type == 'debit':
        updated_bal = profile_bal + trans_amount
    else:
        updated_bal = profile_bal - trans_amount
    current_bal = Profile.objects.filter(user=user).update(balance=updated_bal)

@receiver(post_save, sender=Transactions)
def update_balance_add(sender, instance, **kwards):
    trans = Transactions.objects.get(id=instance.id)
    trans_type = trans.transactions_type

    user = instance.author
    profile_bal = Profile.objects.get(user=user).balance
    trans_amount = trans.amount

    if trans_type == 'debit':
        updated_bal = profile_bal - trans_amount
    else:
        updated_bal = profile_bal + trans_amount
    current_bal = Profile.objects.filter(user=user).update(balance=updated_bal)

Backend/templates/register/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="container">
  <div class="budget">
    <h2 class="left">Expenses</h2>
    <div class="table-container">
      <table>
        <thead>
          <tr>
            <th>Code</th>
            <th>Date</th>
            <th>Transaction Description</th>
            <th>Amount</th>
            <th>Reconcile</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for tran in transactions %}
          <tr>
            <td>{{tran.code}}</td>
            <td>{{tran.date}}</td>
            <td>{{tran.transactions_description}}</td>
            <td>${{tran.amount}}</td>
            <td></td>
            <td>
              <a class="" href="{% url 'register:tran_del' tran.id %}"><i class="material-icons">close</i></a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <a class="add-btn right btn-floating btn-large waves-effect waves-light red modal-trigger" href="#modal1"><i class="material-icons">add</i></a>
  </div>
  <div id="modal1" class="modal">
    <div class="modal-content">
      <form method="post">
        {% csrf_token %}
        <div class="">
          {{form.as_p}}
        </div>


        <div class="modal-footer">
          <input value="add" type="submit" class="modal-close waves-effect waves-green btn-flat">
        </div>
      </form>
    </div>
</section>
{% endblock %}

Backend/templates/register/index2.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
  <div class="">
    <h3 class="right-align">Balance: ${{bal}}</h3>
  </div>
  <div class="table-container">
    <table class="striped ">
      <thead>

        <tr>
          <th>Code</th>
          <th>Date</th>
          <th>Transaction Description</th>
          <th>Amount</th>
          <th>Reconcile</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        {% for tran in transactions %}
        <tr>
          <td>{{tran.code}}</td>
          <td>{{tran.date}}</td>
          <td>{{tran.transactions_description}}</td>
          <td>${{tran.amount}}</td>
          <td></td>
          <td>
            <a class="" href="{% url 'register:tran_del' tran.id %}"><i class="material-icons">close</i></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <a class="add-btn right btn-floating btn-large waves-effect waves-light red modal-trigger" href="#modal1"><i class="material-icons">add</i></a>
</div>
<div id="modal1" class="modal">
  <form method="post">
    {% csrf_token %}
    <div class="modal-content">

      {{form}}

    </div>
    <div class="modal-footer">
      <input value="add" type="submit" class="modal-close waves-effect waves-green btn-flat">
    </div>

  </form>
</div>
{% endblock %}

Backend/templates/register/legend.html
{% extends "base.html" %}
{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'register/css/legend.css' %}">
{% endblock %}
{% block content %}
<div class="container">
  <h2 class="left">Legend</h2>
  <div class="table-container">
    <table>
      <thead>
        <tr>
          <th>Number</th>
          <th>Transaction Category</th>
          <th>Transaction Type</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for sym in legend %}
        <tr>
          <td>{{sym.code}}</td>
          <td>{{sym.transactions_category}}</td>
          <td>{{sym.transactions_type}}</td>
          <td>
            <a class="" href="{% url 'register:code_del' sym.id %}"><i class="material-icons">close</i></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <a class="add-btn right btn-floating btn-large waves-effect waves-light red modal-trigger" href="#modal1"><i class="material-icons">add</i></a>
</div>
<div id="modal1" class="modal">
  <form method="post">
    {% csrf_token %}
    <div class="modal-content">
      {{form}}
    </div>
    <div class="modal-footer">
      <input type="submit" class="modal-close waves-effect waves-green btn-flat">

    </div>
  </form>
</div>
{% endblock %}