Backend/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.login_user_view, name='login'),
    path('signup/', views.create_user_view, name='signup'),
    path('logout/', views.logout_user_view, name='logout'),
]

Backend/checkbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls')),
    path('', include('accounts.urls')),
]

Backend/register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.TransactionListView.as_view(), name='trans_list'),
    path('<int:id>/transaction/', views.TransactionDeleteView.as_view(), name='tran_del'),
    path('legend/', views.LegendCodeListView.as_view(), name='legend_code_list'),
    path('<int:id>/legend/', views.LegendCodeDeleteView.as_view(), name='code_del'),
]

Backend/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="{% static 'register/css/materialize.min.css' %}" media="screen,projection" />

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>
  <header>
    <nav class="top-nav">

      <div class="nav-wrapper">
        <a href="#!" class="brand-logo">Mnemosyne</a>
        <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li>
            <a href="{% url 'register:trans_list' %}">Transactions</a>
          </li>
          <li>
            <a href="{% url 'register:legend_code_list' %}">Legend</a>
          </li>
          <li>
            <a href="{% url 'accounts:logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="">
      <ul id="slide-out" class="sidenav">
        <li>
          <a href="{% url 'register:trans_list' %}">Transactions</a>
        </li>
        <li>
          <a href="{% url 'register:legend_code_list' %}">Legend</a>
        </li>
        <li>
          <a href="{% url 'accounts:logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>

  <!--JavaScript at end of body for optimized loading-->
  <script type="text/javascript" src="{% static 'register/js/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'register/js/materialize.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'register/js/script.js' %}"></script>
</body>

</html>

Backend/templates/base_auth.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="{% static 'register/css/materialize.min.css' %}" media="screen,projection" />

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
  <header>
    <nav class="top-nav">
      <div class="nav-wrapper">
        <a href="#!" class="brand-logo">Mnemosyne</a>
      </div>
    </nav>

  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>

  <!--JavaScript at end of body for optimized loading-->
  <script type="text/javascript" src="{% static 'register/js/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'register/js/materialize.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'register/js/script.js' %}"></script>
</body>

</html>